# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: TestProject tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Create env file
      run: |
        touch .env
        echo TP_API_KEY=${{ secrets.TP_API_KEY }} >> .env
        echo TP_DEV_TOKEN=${{ secrets.TP_DEV_TOKEN }} >> .env
    - name: Run TestProject Agent
      env:
        TP_API_KEY: ${{ secrets.TP_API_KEY }} 
        TP_DEV_TOKEN: ${{ secrets.TP_DEV_TOKEN }}   
      run: |
        cat docker-compose.yml
        docker-compose -f docker-compose.yml up -d
    - name: Run tests
      run: mvn clean test -DtestSuite=suite
